---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[cloudwatch-logs::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
